// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ai} from '../models';
import {fsutil} from '../models';
import {terminal} from '../models';

export function Chat(arg1:string):Promise<ai.Reply>;

export function ClearChat():Promise<void>;

export function GetAIStatus():Promise<ai.Status>;

export function GetProjectRoot():Promise<string>;

export function ListDir(arg1:string):Promise<Array<fsutil.DirEntry>>;

export function MapProjectTree(arg1:number):Promise<fsutil.TreeNode>;

export function OpenProject():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function RunCommand(arg1:string,arg2:string):Promise<terminal.Result>;

export function SetAIMode(arg1:string):Promise<string>;

export function SetGeminiAPIKey(arg1:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
