// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chat(arg1) {
  return window['go']['main']['App']['Chat'](arg1);
}

export function ClearChat() {
  return window['go']['main']['App']['ClearChat']();
}

export function GetAIStatus() {
  return window['go']['main']['App']['GetAIStatus']();
}

export function GetChatHistory() {
  return window['go']['main']['App']['GetChatHistory']();
}

export function GetProjectRoot() {
  return window['go']['main']['App']['GetProjectRoot']();
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function MapProjectTree(arg1) {
  return window['go']['main']['App']['MapProjectTree'](arg1);
}

export function OpenProject() {
  return window['go']['main']['App']['OpenProject']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RunCommand(arg1, arg2) {
  return window['go']['main']['App']['RunCommand'](arg1, arg2);
}

export function SetAIMode(arg1) {
  return window['go']['main']['App']['SetAIMode'](arg1);
}

export function SetGeminiAPIKey(arg1) {
  return window['go']['main']['App']['SetGeminiAPIKey'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
